import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import fetcher from '@/utils/fetcher'
import ImageOfTheDay from '@/components/ImageOfTheDay'
import { Image } from '@/types'
import LastTenDayImages from '@/components/LastTenDayImages'

type HomeProps = {
  imageOfTheDay: Image
  last10DaysImages: Image[]
}

export default function Home ({ imageOfTheDay, last10DaysImages }: HomeProps) {
  console.log(imageOfTheDay)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Home</h1>
        <ImageOfTheDay {...imageOfTheDay} />
        <LastTenDayImages images={last10DaysImages} />

      </main>
    </>
  )
}

// export async function getServerSideProps () {
//   try {
//     const imageOfTheDay = await fetcher()
//     const last10DaysImages = await fetcher('&start_date=2023-03-01&end_date=2023-03-10')

//     return {
//       props: {
//         imageOfTheDay,
//         last10DaysImages
//       }
//     }
//   } catch (error) {
//     return error
//   }
// }

export async function getStaticProps () {
  try {
    const imageOfTheDay = await fetcher()
    const last10DaysImages = await fetcher('&start_date=2023-03-01&end_date=2023-03-10')

    return {
      props: {
        imageOfTheDay,
        last10DaysImages
      }
    }
  } catch (error) {
    return error
  }
}
